name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Go to project root
            cd /var/www/fast_pizza_react

            # Fetch latest code
            git fetch origin main
            git reset --hard origin/main

            # Clean old dependencies and previous build
            rm -rf node_modules
            rm -rf dist

            # Install dependencies and build
            npm install --production
            npm run build

            # Restart all PM2 apps
            pm2 restart all || true
