name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          timeout: 30m
          script: |
            cd /var/www/fast_pizza_react
            git fetch origin main
            git reset --hard origin/main

            rm -rf node_modules dist
            npm cache clean --force

            # Install all dependencies (including dev for Vite plugins)
            npm install

            # Set production environment
            export NODE_ENV=production

            # Build project
            npm run build

            # Restart PM2
            pm2 restart || true 